name: LitTournaments
version: '${project.version}'
main: me.waterarchery.littournaments.LitTournaments
api-version: '1.16'
authors: [ WaterArchery ]
description: Create fun tournaments for players
folia-supported: true
libraries:
  - org.hibernate.orm:hibernate-hikaricp:6.6.13.Final
  - org.hibernate.orm:hibernate-core:6.6.13.Final
  - com.h2database:h2:2.3.232
  - com.zaxxer:HikariCP:6.2.1
  - org.mariadb.jdbc:mariadb-java-client:3.5.3
  - mysql:mysql-connector-java:8.0.33
softdepend:
  - NuVotifier
  - Votifier
  - CrazyCrates
  - ExcellentCrates
  - Essentials
  - EssentialsX
  - Duels
  - MythicMobs
  - RivalHarvesterHoes
  - EvenMoreFish
  - ShopGuiPlus