name: LitTournaments
version: '${project.version}'
main: me.waterarchery.littournaments.LitTournaments
api-version: '1.16'
authors: [ WaterArchery ]
description: Create fun tournaments for players
folia-supported: true
libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.5.2
  - com.zaxxer:HikariCP:6.0.0
softdepend:
  - NuVotifier
  - Votifier
  - CrazyCrates
  - ExcellentCrates
  - Essentials
  - EssentialsX
  - Duels
  - MythicMobs
  - RivalHarvesterHoes
  - EvenMoreFish
  - ShopGuiPlus
depend:
  - LitLibs